Add files via upload
sirjonasxx/G-ExtensionStore pull request #118
Opened 2023-02-12 17:19 UTC by iamyarkin

2023-02-12 17:24 UTC, WiredSpast requested changes

2023-02-12 17:24 UTC, WiredSpast commented on store/extensions/GChatSaver/extension.json
> +    "title": "GChat-Saver",
Make sure the name of the folder and the title of the extension are the same, so add a dash to the name of the folder or remove it here

2023-02-12 17:26 UTC, WiredSpast commented
Your icon appears to be rectangular, it will be formatted to a square in the store so it light look a bit stretched

2023-02-12 18:16 UTC, WiredSpast commented
The screenshot has to be named screenshot.png

2023-02-12 19:05 UTC, iamyarkin commented
done

2023-02-12 21:56 UTC, WiredSpast requested changes

2023-02-12 21:56 UTC, WiredSpast commented on store/extensions/GChatSaver/extension.json
> +      "version": "1.0"
The current version of G-Python is 0.1.6
```suggestion
      "version": "0.1.6"
```

2023-02-13 11:27 UTC, WiredSpast commented
Apparently the screenshot is too big 
![image](https://user-images.githubusercontent.com/74211155/218445691-04d52dea-2895-48e7-8bc0-33e2e382848e.png)

2023-02-13 15:41 UTC, iamyarkin commented
is it done

2023-02-13 15:58 UTC, merged