feat: Add EventSender Extension
sirjonasxx/G-ExtensionStore pull request #121
Opened 2023-03-28 22:34 UTC by thauanvargas

Will create a read me later !

2023-03-28 22:40 UTC, WiredSpast requested changes
The zip file must be named `extension.zip`

2023-03-28 22:40 UTC, WiredSpast commented on store/extensions/EventSender/extension.json
> +  "title": "Event Sender",
Make sure the name of the folder and the title are the exact same, so either add a space to the folder name, or remove it from the title
![image](https://user-images.githubusercontent.com/74211155/228382565-8deaa57a-abd7-4d3f-907a-31f607875752.png)

2023-03-28 22:43 UTC, JonasssC commented on store/extensions/EventSender/extension.json
> +    "default": ["java", "-jar", "EventSender.jar", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
The jar in the zip is named `EventSender_v1.0.jar` so the command should also have that as the file name, or the file name should be changed

2023-03-28 22:44 UTC, WiredSpast commented on store/extensions/EventSender/extension.json
> +    "default": ["java", "-jar", "EventSender.jar", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
The jar file in the zip folder has a different name, make sure it matches with the one in the command 
![image](https://user-images.githubusercontent.com/74211155/228383463-a727b458-acb9-4c2f-82ba-6748160cc63e.png)

2023-03-28 22:49 UTC, WiredSpast commented on store/extensions/EventSender/extension.json
> +    "default": ["java", "-jar", "EventSender.jar", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
The code in the jar file also doesn't match with the one in the repository

![image](https://user-images.githubusercontent.com/74211155/228384014-51daa240-6d7f-4dce-8512-6880bb8943bc.png)

![image](https://user-images.githubusercontent.com/74211155/228384029-58daeb37-b298-47d2-b3e7-555ecb1022ab.png)

2023-03-28 22:57 UTC, thauanvargas commented on store/extensions/EventSender/extension.json
> +    "default": ["java", "-jar", "EventSender.jar", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
Oops wrong extension added, thanks for noticing, updated

2023-03-28 22:57 UTC, thauanvargas commented on store/extensions/EventSender/extension.json
> +  "title": "Event Sender",
Updated on commit [10aa780](https://github.com/sirjonasxx/G-ExtensionStore/pull/121/commits/10aa780e3b9eb4ce3fa5626ccae8b73b048bb1d3)

2023-03-30 07:20 UTC, WiredSpast approved these changes

2023-03-30 07:21 UTC, merged