Add Quick Pickup Utils v1.0.0
sirjonasxx/G-ExtensionStore pull request #209
Opened 2024-07-09 21:39 UTC by SimonFlapse

Quick Pickup Utils G-Earth Extension for Habbo Hotel: Origins

Supports the chat command
`:pickup <wall | floor> <amount>` allowing for versatile pickup of items in your Habbo Hotel: Origins room
Examples:
- `:pickup wall` to pick up all wall items
- `:pickup floor` to pick up all floor items
- `:pickup wall 10` to pick up 10 wall items
- `:pickup floor 5` to pick up 5 floor items
- `:pickup 8` to pickup 8 items starting with wall items and then floor items if there is less than 8 wall items

`:pickup <item_name> <amount>` allowing picking up stacks of the same item in your Habbo Hotel: Origins room
Examples:
- `:pickup rare_daffodil_rug` to pick up all Petals Patches
- `:pickup poster_5000 10` to pick up 10 Purple Garlands

### Additional notes
I've created this plugin primarily as an example project to explore a library for parsing packets from Habbo Hotel: Origins for Java.

Let me know if there is something missing - Thanks!

2024-07-09 21:48 UTC, WiredSpast requested changes

2024-07-09 21:48 UTC, WiredSpast commented on store/extensions/QuickPickupUtils/extension.json
> +  "title": "Quick Pickup Utils",
The title and folder name have to be the exact same, you can add spaces in the folder name

2024-07-09 21:48 UTC, WiredSpast commented on store/extensions/QuickPickupUtils/extension.json
> +  "description": "Chat commands to quickly pickup items in your Habbo flat",
I would recommend adding the commands in here, you can use `\n` to add line breaks

2024-07-09 21:48 UTC, WiredSpast commented on store/extensions/QuickPickupUtils/extension.json
> +    "version": "1.5.4"
```suggestion
    "version": "1.5.4-beta-6"
```

2024-07-09 21:49 UTC, WiredSpast commented on store/extensions/QuickPickupUtils/extension.json
> +  "description": "Chat commands to quickly pickup items in your Habbo flat",
Most end users won't realize that there is a read me with more info in it

2024-07-09 21:49 UTC, SimonFlapse commented
Thanks for the extremely quick review, I'll get it sorted. Thanks ❤️

2024-07-10 14:52 UTC, WiredSpast approved these changes

2024-07-10 14:52 UTC, merged