friend remover v.0.1
sirjonasxx/G-ExtensionStore pull request #44
Opened 2021-09-29 16:29 UTC by Tragic7432

2021-09-29 18:09 UTC, Alynva requested changes

2021-09-29 18:09 UTC, Alynva commented on store/extensions/Friend Remover/extension.json
> +    "language": "Java",
language should be "Python"

2021-09-29 18:14 UTC, Alynva commented
i don't know a lot of python, but the handler souldn't be like

```python
def start(self, s):
```
?

2021-09-29 18:31 UTC, Tragic7432 commented on store/extensions/Friend Remover/extension.json
> +    "language": "Java",
done

2021-09-29 18:32 UTC, Alynva approved these changes

2021-09-29 18:32 UTC, Tragic7432 commented
> i don't know a lot of python, but the handler souldn't be like
> 
> ```python
> def start(self, s):
> ```
> 
> ?

I dont use init method so no need for "self".

2021-09-30 17:08 UTC, sirjonasxx commented
`friendremover.zip` -> `extension.zip`

2021-09-30 17:13 UTC, Alynva commented
> `friendremover.zip` -> `extension.zip`

That file should be removed. Another `extension.zip` already exists

2021-09-30 17:27 UTC, merged