Mod Tools
sirjonasxx/G-ExtensionStore pull request #82
Opened 2022-04-03 21:24 UTC by funkydemir66

Mod Tools for G-Earth

2022-04-03 21:25 UTC, funkydemir66 commented
dude... i finally opened it

2022-04-03 23:21 UTC, Alynva requested changes
the extension should be in a `.zip` file, instead of `.rar`

2022-04-03 23:21 UTC, Alynva commented on store/extensions/Mod Tools/extension.json
> +    "commands": :mt pla/:mt mute (minute)/:mt rmute {
something is wrong here

2022-04-03 23:22 UTC, Alynva commented
Also, that's not an screenshot

2022-04-04 06:48 UTC, WiredSpast commented on store/extensions/Mod Tools/extension.json
> +    "updateDate": "03-04-2002 13:38:00",
What year is it? xD

2022-04-04 06:49 UTC, WiredSpast commented on store/extensions/Mod Tools/extension.json
> +      "version": "2.0"
Also this version of G-Python doesn't appear to exist

2022-04-04 06:52 UTC, WiredSpast commented on store/extensions/Mod Tools/extension.json
> +        "twitter": ""
Also it's better to just leave out the twitter line instead of given it an empty string

2022-04-04 07:00 UTC, WiredSpast commented
I've corrected the extension.json file for you so you have an example for next time, but you will have to replace the `extensions.rar` file with a `extension.zip` file yourself

2022-04-04 11:57 UTC, funkydemir66 commented
I'm freaking out :D

2022-04-04 12:03 UTC, WiredSpast commented
![image](https://user-images.githubusercontent.com/74211155/161539709-0021f1ef-cc2a-471c-9ec4-eb59577612e7.png)
![image](https://user-images.githubusercontent.com/74211155/161539742-97f907a3-2143-4931-b790-adc4305ee742.png)

2022-04-04 12:04 UTC, WiredSpast commented
extension.zip not extensions.zip and the .rar file has to be removed from github

2022-04-04 12:11 UTC, funkydemir66 commented
I'll take care of it and deliver it, I'm at the library right now

2022-04-04 12:13 UTC, funkydemir66 commented
i make extension.zip

2022-04-04 12:17 UTC, funkydemir66 commented
I think everything is ok except the screenshot.

thanks for your help i will do it as soon as possible :P

2022-04-04 12:27 UTC, WiredSpast commented
- You might want to fix a small big as well, when you enter something that isn't a number with the `:mt mute ...` command the extension will crash and the user's entire client will get stuck.
![image](https://user-images.githubusercontent.com/74211155/161542680-560918d7-41f1-4a41-a803-07765b4af90a.png)


- Also I would recommend to use either one of these 2 packages (they get send when you click on a user) to identify the user instead of the Unmute user button within the ambassador tools, because if someone has Client-side staff permissions disabled they won't have access to the ambassador tools
![image](https://user-images.githubusercontent.com/74211155/161543087-537e8723-1f73-4e5b-bf63-be2cf6fdcd86.png)

2022-04-04 12:49 UTC, funkydemir66 commented
A few hours later v/

2022-04-04 12:51 UTC, funkydemir66 commented
ayrıca (tıkladığınızda gönderilirler) bir kullanım etkili değildir

anyway thanks for the advice

2022-04-04 13:15 UTC, funkydemir66 commented
okey is finished

2022-04-04 15:06 UTC, funkydemir66 commented
there are a few mistakes for now i will tell you when i get it done

2022-04-04 16:48 UTC, funkydemir66 commented
ok work is done all bugs is fixed

2022-04-04 17:10 UTC, WiredSpast commented
`extension.zip` not a loose py file 
![image](https://user-images.githubusercontent.com/74211155/161596065-2c23f9bd-d8d7-444d-91db-b03cff46ef9d.png)

2022-04-04 17:13 UTC, WiredSpast commented
Also maybe add a explanation of what the command do exactly either in the description part of the `extension.json` file or a readme in the repo, because it's really not clear what they would do

2022-04-04 17:39 UTC, funkydemir66 commented
okey i upgraded

2022-04-04 17:40 UTC, Alynva commented on store/extensions/Mod Tools/extension.json
> +    ",
remove this line break

2022-04-04 17:42 UTC, WiredSpast commented
If you want a linebreak in the actual page you have to use `\n`

2022-04-04 17:43 UTC, funkydemir66 commented
okey

2022-04-04 17:48 UTC, funkydemir66 commented
its finished

2022-04-04 17:52 UTC, merged