MultiWhisper
sirjonasxx/G-ExtensionStore pull request #87
Opened 2022-04-05 21:33 UTC by funkydemir66

MultiWhisper 1.0

2022-04-05 22:45 UTC, Alynva requested changes
The icon mush be less than 80x80

2022-04-06 01:18 UTC, Alynva requested changes

2022-04-06 01:18 UTC, Alynva commented on store/extensions/MultiWhisper/extension.json
> +    "title": "Mod Tools",
The extension title must match the folder name

2022-04-06 04:03 UTC, funkydemir66 commented
okey is finish

2022-04-06 12:32 UTC, funkydemir66 commented
yh?

2022-04-06 12:32 UTC, closed without merging