MultiWhisper
sirjonasxx/G-ExtensionStore pull request #88
Opened 2022-04-06 12:35 UTC by funkydemir66

MultiWhisper for G Earth

2022-04-06 14:45 UTC, Alynva requested changes

2022-04-06 14:45 UTC, Alynva commented on store/extensions/MultiWhisper/extension.json
> +    "title": "Multi Whisper",
Remove the space in the title, or add it in the folder's name

2022-04-06 14:58 UTC, funkydemir66 commented
okey finished

2022-04-06 15:00 UTC, Alynva approved these changes

2022-04-06 16:03 UTC, WiredSpast requested changes

2022-04-06 16:03 UTC, WiredSpast commented on store/extensions/MultiWhisper/extension.json
> +      "default": ["python", "ModTools.py", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
This doesn't seem right

2022-04-06 16:10 UTC, Alynva requested changes

2022-04-06 16:10 UTC, Alynva commented on store/extensions/MultiWhisper/extension.json
> +      "default": ["python", "ModTools.py", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
Yeah, it should be `MultiWhisper.py`

2022-04-06 16:16 UTC, funkydemir66 commented on store/extensions/MultiWhisper/extension.json
> +      "default": ["python", "ModTools.py", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
its okey

2022-04-06 16:17 UTC, funkydemir66 commented on store/extensions/MultiWhisper/extension.json
> +      "default": ["python", "ModTools.py", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
ty for helps

2022-04-06 16:17 UTC, WiredSpast approved these changes

2022-04-06 16:25 UTC, Alynva approved these changes

2022-04-06 16:51 UTC, funkydemir66 commented
okey?

2022-04-06 20:46 UTC, funkydemir66 commented
wh

2022-04-07 16:52 UTC, Alynva requested changes
Please, try to not submit two extensions in the same PR.

2022-04-07 16:52 UTC, Alynva commented on store/extensions/RollerWalk/extension.json
> +    "title": "Multi Whisper",
Your extension.json of the RollerWalk isn't right.

2022-04-07 16:53 UTC, WiredSpast commented
> Please, try to not submit two extensions in the same PR.

That actually doesn't matter

2022-04-07 16:58 UTC, funkydemir66 commented on store/extensions/RollerWalk/extension.json
> +    "title": "Multi Whisper",
yes i will do it there

2022-04-07 16:58 UTC, Alynva commented
> > Please, try to not submit two extensions in the same PR.
> 
> That actually doesn't matter

For the tests work I know that doesn't matter, I just think that helps to keep the conversation centralized

2022-04-07 17:04 UTC, funkydemir66 commented
all ok i think

2022-04-10 13:02 UTC, merged